require "rake/extensiontask"
require "rake/testtask"

spec = Gem::Specification.new do |s|
  s.name        = "google-protobuf"
  s.version     = "2.6.2"
  s.licenses    = ["BSD"]
  s.summary     = "Protocol Buffers"
  s.description = "Protocol Buffers are Google's data interchange format."
  s.authors     = ["Protobuf Authors"]
  s.email       = "protobuf@googlegroups.com"
  s.require_paths = ["lib"]
  s.extensions  = ["ext/google/protobuf_c/extconf.rb"]
  s.files       = ["lib/google/protobuf_c.so", "lib/google/protobuf.rb"]
end

Rake::ExtensionTask.new("protobuf_c", spec) do |ext|
  ext.ext_dir = "ext/google/protobuf_c"
  ext.lib_dir = "lib/google"
end

Rake::TestTask.new(:test => :build) do |t|
  t.test_files = FileList["tests/*.rb"]
end

Gem::PackageTask.new(spec) do |pkg|
end

task :build => [:clean, :compile]
task :default => [:build]

# vim:sw=2:et
