require "rake/extensiontask"
require "rake/testtask"

spec = Gem::Specification.new do |s|
  s.name        = "google-protobuf"
  s.version     = "2.6.2"
  s.licenses    = ["BSD"]
  s.summary     = "Protocol Buffers"
  s.description = "Protocol Buffers are Google's data interchange format."
  s.authors     = ["Protobuf Authors"]
  s.email       = "protobuf@googlegroups.com"
  s.require_paths = ["lib"]
  s.extensions  = ["ext/google/protobuf_c/extconf.rb"]
  s.files       = ["lib/google/protobuf_c.so", "lib/google/protobuf.rb"]
end

case RUBY_PLATFORM
when /java/
  require 'rake/javaextensiontask'
  Rake::JavaExtensionTask.new("protobuf_java", spec) do |ext|
    jruby_home = RbConfig::CONFIG['prefix']
    ext.ext_dir = 'ext/java'
    ext.lib_dir = 'lib/google'
    ext.source_version = '1.6'
    ext.target_version = '1.6'
    jars = ["#{jruby_home}/lib/jruby.jar"] + FileList['*.jar']
    ext.classpath = jars.map { |x| File.expand_path x }.join ':'
  end
else # MRI
  Rake::ExtensionTask.new("protobuf_c", spec) do |ext|
    ext.ext_dir = "ext/google/protobuf_c"
    ext.lib_dir = "lib/google"
  end
end

Rake::TestTask.new(:test => :build) do |t|
  t.test_files = FileList["tests/*.rb"]
end

Gem::PackageTask.new(spec) do |pkg|
end

task :build => [:clean, :compile]
task :default => [:build]

# vim:sw=2:et
