// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tests/basic.proto

package basic;

public final class Basic {
  private Basic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code basic.TestEnum}
   */
  public enum TestEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Default = 0;</code>
     */
    Default(0, 0),
    /**
     * <code>A = 1;</code>
     */
    A(1, 1),
    /**
     * <code>B = 2;</code>
     */
    B(2, 2),
    /**
     * <code>C = 3;</code>
     */
    C(3, 3),
    ;

    /**
     * <code>Default = 0;</code>
     */
    public static final int Default_VALUE = 0;
    /**
     * <code>A = 1;</code>
     */
    public static final int A_VALUE = 1;
    /**
     * <code>B = 2;</code>
     */
    public static final int B_VALUE = 2;
    /**
     * <code>C = 3;</code>
     */
    public static final int C_VALUE = 3;


    public final int getNumber() { return value; }

    public static TestEnum valueOf(int value) {
      switch (value) {
        case 0: return Default;
        case 1: return A;
        case 2: return B;
        case 3: return C;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TestEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TestEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TestEnum>() {
            public TestEnum findValueByNumber(int number) {
              return TestEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return basic.Basic.getDescriptor().getEnumTypes().get(0);
    }

    private static final TestEnum[] VALUES = values();

    public static TestEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TestEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:basic.TestEnum)
  }

  public interface TestMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 optional_int32 = 1;
    /**
     * <code>optional int32 optional_int32 = 1;</code>
     */
    boolean hasOptionalInt32();
    /**
     * <code>optional int32 optional_int32 = 1;</code>
     */
    int getOptionalInt32();

    // optional int64 optional_int64 = 2;
    /**
     * <code>optional int64 optional_int64 = 2;</code>
     */
    boolean hasOptionalInt64();
    /**
     * <code>optional int64 optional_int64 = 2;</code>
     */
    long getOptionalInt64();

    // optional uint32 optional_uint32 = 3;
    /**
     * <code>optional uint32 optional_uint32 = 3;</code>
     */
    boolean hasOptionalUint32();
    /**
     * <code>optional uint32 optional_uint32 = 3;</code>
     */
    int getOptionalUint32();

    // optional uint64 optional_uint64 = 4;
    /**
     * <code>optional uint64 optional_uint64 = 4;</code>
     */
    boolean hasOptionalUint64();
    /**
     * <code>optional uint64 optional_uint64 = 4;</code>
     */
    long getOptionalUint64();

    // optional bool optional_bool = 5;
    /**
     * <code>optional bool optional_bool = 5;</code>
     */
    boolean hasOptionalBool();
    /**
     * <code>optional bool optional_bool = 5;</code>
     */
    boolean getOptionalBool();

    // optional float optional_float = 6;
    /**
     * <code>optional float optional_float = 6;</code>
     */
    boolean hasOptionalFloat();
    /**
     * <code>optional float optional_float = 6;</code>
     */
    float getOptionalFloat();

    // optional double optional_double = 7;
    /**
     * <code>optional double optional_double = 7;</code>
     */
    boolean hasOptionalDouble();
    /**
     * <code>optional double optional_double = 7;</code>
     */
    double getOptionalDouble();

    // optional string optional_string = 8;
    /**
     * <code>optional string optional_string = 8;</code>
     */
    boolean hasOptionalString();
    /**
     * <code>optional string optional_string = 8;</code>
     */
    java.lang.String getOptionalString();
    /**
     * <code>optional string optional_string = 8;</code>
     */
    com.google.protobuf.ByteString
        getOptionalStringBytes();

    // optional bytes optional_bytes = 9;
    /**
     * <code>optional bytes optional_bytes = 9;</code>
     */
    boolean hasOptionalBytes();
    /**
     * <code>optional bytes optional_bytes = 9;</code>
     */
    com.google.protobuf.ByteString getOptionalBytes();

    // optional .basic.TestMessage2 optional_msg = 10;
    /**
     * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
     */
    boolean hasOptionalMsg();
    /**
     * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
     */
    basic.Basic.TestMessage2 getOptionalMsg();
    /**
     * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
     */
    basic.Basic.TestMessage2OrBuilder getOptionalMsgOrBuilder();

    // optional .basic.TestEnum optional_enum = 11;
    /**
     * <code>optional .basic.TestEnum optional_enum = 11;</code>
     *
     * <pre>
     *
     *
     *repeated :repeated_int32,  :int32,        12
     *repeated :repeated_int64,  :int64,        13
     *repeated :repeated_uint32, :uint32,       14
     *repeated :repeated_uint64, :uint64,       15
     *repeated :repeated_bool,   :bool,         16
     *repeated :repeated_float,  :float,        17
     *repeated :repeated_double, :double,       18
     *repeated :repeated_string, :string,       19
     *repeated :repeated_bytes,  :bytes,        20
     *repeated :repeated_msg,    :message,      21, "TestMessage2"
     *repeated :repeated_enum,   :enum,         22, "TestEnum"
     * </pre>
     */
    boolean hasOptionalEnum();
    /**
     * <code>optional .basic.TestEnum optional_enum = 11;</code>
     *
     * <pre>
     *
     *
     *repeated :repeated_int32,  :int32,        12
     *repeated :repeated_int64,  :int64,        13
     *repeated :repeated_uint32, :uint32,       14
     *repeated :repeated_uint64, :uint64,       15
     *repeated :repeated_bool,   :bool,         16
     *repeated :repeated_float,  :float,        17
     *repeated :repeated_double, :double,       18
     *repeated :repeated_string, :string,       19
     *repeated :repeated_bytes,  :bytes,        20
     *repeated :repeated_msg,    :message,      21, "TestMessage2"
     *repeated :repeated_enum,   :enum,         22, "TestEnum"
     * </pre>
     */
    basic.Basic.TestEnum getOptionalEnum();
  }
  /**
   * Protobuf type {@code basic.TestMessage}
   */
  public static final class TestMessage extends
      com.google.protobuf.GeneratedMessage
      implements TestMessageOrBuilder {
    // Use TestMessage.newBuilder() to construct.
    private TestMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestMessage defaultInstance;
    public static TestMessage getDefaultInstance() {
      return defaultInstance;
    }

    public TestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              optionalInt32_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              optionalInt64_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              optionalUint32_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              optionalUint64_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              optionalBool_ = input.readBool();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              optionalFloat_ = input.readFloat();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              optionalDouble_ = input.readDouble();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              optionalString_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              optionalBytes_ = input.readBytes();
              break;
            }
            case 82: {
              basic.Basic.TestMessage2.Builder subBuilder = null;
              if (((bitField0_ & 0x00000200) == 0x00000200)) {
                subBuilder = optionalMsg_.toBuilder();
              }
              optionalMsg_ = input.readMessage(basic.Basic.TestMessage2.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(optionalMsg_);
                optionalMsg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000200;
              break;
            }
            case 88: {
              int rawValue = input.readEnum();
              basic.Basic.TestEnum value = basic.Basic.TestEnum.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(11, rawValue);
              } else {
                bitField0_ |= 0x00000400;
                optionalEnum_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return basic.Basic.internal_static_basic_TestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return basic.Basic.internal_static_basic_TestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              basic.Basic.TestMessage.class, basic.Basic.TestMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<TestMessage> PARSER =
        new com.google.protobuf.AbstractParser<TestMessage>() {
      public TestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 optional_int32 = 1;
    public static final int OPTIONAL_INT32_FIELD_NUMBER = 1;
    private int optionalInt32_;
    /**
     * <code>optional int32 optional_int32 = 1;</code>
     */
    public boolean hasOptionalInt32() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 optional_int32 = 1;</code>
     */
    public int getOptionalInt32() {
      return optionalInt32_;
    }

    // optional int64 optional_int64 = 2;
    public static final int OPTIONAL_INT64_FIELD_NUMBER = 2;
    private long optionalInt64_;
    /**
     * <code>optional int64 optional_int64 = 2;</code>
     */
    public boolean hasOptionalInt64() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 optional_int64 = 2;</code>
     */
    public long getOptionalInt64() {
      return optionalInt64_;
    }

    // optional uint32 optional_uint32 = 3;
    public static final int OPTIONAL_UINT32_FIELD_NUMBER = 3;
    private int optionalUint32_;
    /**
     * <code>optional uint32 optional_uint32 = 3;</code>
     */
    public boolean hasOptionalUint32() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 optional_uint32 = 3;</code>
     */
    public int getOptionalUint32() {
      return optionalUint32_;
    }

    // optional uint64 optional_uint64 = 4;
    public static final int OPTIONAL_UINT64_FIELD_NUMBER = 4;
    private long optionalUint64_;
    /**
     * <code>optional uint64 optional_uint64 = 4;</code>
     */
    public boolean hasOptionalUint64() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 optional_uint64 = 4;</code>
     */
    public long getOptionalUint64() {
      return optionalUint64_;
    }

    // optional bool optional_bool = 5;
    public static final int OPTIONAL_BOOL_FIELD_NUMBER = 5;
    private boolean optionalBool_;
    /**
     * <code>optional bool optional_bool = 5;</code>
     */
    public boolean hasOptionalBool() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool optional_bool = 5;</code>
     */
    public boolean getOptionalBool() {
      return optionalBool_;
    }

    // optional float optional_float = 6;
    public static final int OPTIONAL_FLOAT_FIELD_NUMBER = 6;
    private float optionalFloat_;
    /**
     * <code>optional float optional_float = 6;</code>
     */
    public boolean hasOptionalFloat() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional float optional_float = 6;</code>
     */
    public float getOptionalFloat() {
      return optionalFloat_;
    }

    // optional double optional_double = 7;
    public static final int OPTIONAL_DOUBLE_FIELD_NUMBER = 7;
    private double optionalDouble_;
    /**
     * <code>optional double optional_double = 7;</code>
     */
    public boolean hasOptionalDouble() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double optional_double = 7;</code>
     */
    public double getOptionalDouble() {
      return optionalDouble_;
    }

    // optional string optional_string = 8;
    public static final int OPTIONAL_STRING_FIELD_NUMBER = 8;
    private java.lang.Object optionalString_;
    /**
     * <code>optional string optional_string = 8;</code>
     */
    public boolean hasOptionalString() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string optional_string = 8;</code>
     */
    public java.lang.String getOptionalString() {
      java.lang.Object ref = optionalString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          optionalString_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string optional_string = 8;</code>
     */
    public com.google.protobuf.ByteString
        getOptionalStringBytes() {
      java.lang.Object ref = optionalString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        optionalString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes optional_bytes = 9;
    public static final int OPTIONAL_BYTES_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString optionalBytes_;
    /**
     * <code>optional bytes optional_bytes = 9;</code>
     */
    public boolean hasOptionalBytes() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bytes optional_bytes = 9;</code>
     */
    public com.google.protobuf.ByteString getOptionalBytes() {
      return optionalBytes_;
    }

    // optional .basic.TestMessage2 optional_msg = 10;
    public static final int OPTIONAL_MSG_FIELD_NUMBER = 10;
    private basic.Basic.TestMessage2 optionalMsg_;
    /**
     * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
     */
    public boolean hasOptionalMsg() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
     */
    public basic.Basic.TestMessage2 getOptionalMsg() {
      return optionalMsg_;
    }
    /**
     * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
     */
    public basic.Basic.TestMessage2OrBuilder getOptionalMsgOrBuilder() {
      return optionalMsg_;
    }

    // optional .basic.TestEnum optional_enum = 11;
    public static final int OPTIONAL_ENUM_FIELD_NUMBER = 11;
    private basic.Basic.TestEnum optionalEnum_;
    /**
     * <code>optional .basic.TestEnum optional_enum = 11;</code>
     *
     * <pre>
     *
     *
     *repeated :repeated_int32,  :int32,        12
     *repeated :repeated_int64,  :int64,        13
     *repeated :repeated_uint32, :uint32,       14
     *repeated :repeated_uint64, :uint64,       15
     *repeated :repeated_bool,   :bool,         16
     *repeated :repeated_float,  :float,        17
     *repeated :repeated_double, :double,       18
     *repeated :repeated_string, :string,       19
     *repeated :repeated_bytes,  :bytes,        20
     *repeated :repeated_msg,    :message,      21, "TestMessage2"
     *repeated :repeated_enum,   :enum,         22, "TestEnum"
     * </pre>
     */
    public boolean hasOptionalEnum() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional .basic.TestEnum optional_enum = 11;</code>
     *
     * <pre>
     *
     *
     *repeated :repeated_int32,  :int32,        12
     *repeated :repeated_int64,  :int64,        13
     *repeated :repeated_uint32, :uint32,       14
     *repeated :repeated_uint64, :uint64,       15
     *repeated :repeated_bool,   :bool,         16
     *repeated :repeated_float,  :float,        17
     *repeated :repeated_double, :double,       18
     *repeated :repeated_string, :string,       19
     *repeated :repeated_bytes,  :bytes,        20
     *repeated :repeated_msg,    :message,      21, "TestMessage2"
     *repeated :repeated_enum,   :enum,         22, "TestEnum"
     * </pre>
     */
    public basic.Basic.TestEnum getOptionalEnum() {
      return optionalEnum_;
    }

    private void initFields() {
      optionalInt32_ = 0;
      optionalInt64_ = 0L;
      optionalUint32_ = 0;
      optionalUint64_ = 0L;
      optionalBool_ = false;
      optionalFloat_ = 0F;
      optionalDouble_ = 0D;
      optionalString_ = "";
      optionalBytes_ = com.google.protobuf.ByteString.EMPTY;
      optionalMsg_ = basic.Basic.TestMessage2.getDefaultInstance();
      optionalEnum_ = basic.Basic.TestEnum.Default;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, optionalInt32_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, optionalInt64_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, optionalUint32_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, optionalUint64_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, optionalBool_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, optionalFloat_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, optionalDouble_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getOptionalStringBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, optionalBytes_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(10, optionalMsg_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeEnum(11, optionalEnum_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, optionalInt32_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, optionalInt64_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, optionalUint32_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, optionalUint64_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, optionalBool_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, optionalFloat_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, optionalDouble_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getOptionalStringBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, optionalBytes_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, optionalMsg_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, optionalEnum_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static basic.Basic.TestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static basic.Basic.TestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static basic.Basic.TestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static basic.Basic.TestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static basic.Basic.TestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static basic.Basic.TestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static basic.Basic.TestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static basic.Basic.TestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static basic.Basic.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static basic.Basic.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(basic.Basic.TestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code basic.TestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements basic.Basic.TestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return basic.Basic.internal_static_basic_TestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return basic.Basic.internal_static_basic_TestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                basic.Basic.TestMessage.class, basic.Basic.TestMessage.Builder.class);
      }

      // Construct using basic.Basic.TestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOptionalMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        optionalInt32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        optionalInt64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        optionalUint32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        optionalUint64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        optionalBool_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        optionalFloat_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        optionalDouble_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        optionalString_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        optionalBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        if (optionalMsgBuilder_ == null) {
          optionalMsg_ = basic.Basic.TestMessage2.getDefaultInstance();
        } else {
          optionalMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        optionalEnum_ = basic.Basic.TestEnum.Default;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return basic.Basic.internal_static_basic_TestMessage_descriptor;
      }

      public basic.Basic.TestMessage getDefaultInstanceForType() {
        return basic.Basic.TestMessage.getDefaultInstance();
      }

      public basic.Basic.TestMessage build() {
        basic.Basic.TestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public basic.Basic.TestMessage buildPartial() {
        basic.Basic.TestMessage result = new basic.Basic.TestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.optionalInt32_ = optionalInt32_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.optionalInt64_ = optionalInt64_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.optionalUint32_ = optionalUint32_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.optionalUint64_ = optionalUint64_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.optionalBool_ = optionalBool_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.optionalFloat_ = optionalFloat_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.optionalDouble_ = optionalDouble_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.optionalString_ = optionalString_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.optionalBytes_ = optionalBytes_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (optionalMsgBuilder_ == null) {
          result.optionalMsg_ = optionalMsg_;
        } else {
          result.optionalMsg_ = optionalMsgBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.optionalEnum_ = optionalEnum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof basic.Basic.TestMessage) {
          return mergeFrom((basic.Basic.TestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(basic.Basic.TestMessage other) {
        if (other == basic.Basic.TestMessage.getDefaultInstance()) return this;
        if (other.hasOptionalInt32()) {
          setOptionalInt32(other.getOptionalInt32());
        }
        if (other.hasOptionalInt64()) {
          setOptionalInt64(other.getOptionalInt64());
        }
        if (other.hasOptionalUint32()) {
          setOptionalUint32(other.getOptionalUint32());
        }
        if (other.hasOptionalUint64()) {
          setOptionalUint64(other.getOptionalUint64());
        }
        if (other.hasOptionalBool()) {
          setOptionalBool(other.getOptionalBool());
        }
        if (other.hasOptionalFloat()) {
          setOptionalFloat(other.getOptionalFloat());
        }
        if (other.hasOptionalDouble()) {
          setOptionalDouble(other.getOptionalDouble());
        }
        if (other.hasOptionalString()) {
          bitField0_ |= 0x00000080;
          optionalString_ = other.optionalString_;
          onChanged();
        }
        if (other.hasOptionalBytes()) {
          setOptionalBytes(other.getOptionalBytes());
        }
        if (other.hasOptionalMsg()) {
          mergeOptionalMsg(other.getOptionalMsg());
        }
        if (other.hasOptionalEnum()) {
          setOptionalEnum(other.getOptionalEnum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        basic.Basic.TestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (basic.Basic.TestMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 optional_int32 = 1;
      private int optionalInt32_ ;
      /**
       * <code>optional int32 optional_int32 = 1;</code>
       */
      public boolean hasOptionalInt32() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 optional_int32 = 1;</code>
       */
      public int getOptionalInt32() {
        return optionalInt32_;
      }
      /**
       * <code>optional int32 optional_int32 = 1;</code>
       */
      public Builder setOptionalInt32(int value) {
        bitField0_ |= 0x00000001;
        optionalInt32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 optional_int32 = 1;</code>
       */
      public Builder clearOptionalInt32() {
        bitField0_ = (bitField0_ & ~0x00000001);
        optionalInt32_ = 0;
        onChanged();
        return this;
      }

      // optional int64 optional_int64 = 2;
      private long optionalInt64_ ;
      /**
       * <code>optional int64 optional_int64 = 2;</code>
       */
      public boolean hasOptionalInt64() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 optional_int64 = 2;</code>
       */
      public long getOptionalInt64() {
        return optionalInt64_;
      }
      /**
       * <code>optional int64 optional_int64 = 2;</code>
       */
      public Builder setOptionalInt64(long value) {
        bitField0_ |= 0x00000002;
        optionalInt64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 optional_int64 = 2;</code>
       */
      public Builder clearOptionalInt64() {
        bitField0_ = (bitField0_ & ~0x00000002);
        optionalInt64_ = 0L;
        onChanged();
        return this;
      }

      // optional uint32 optional_uint32 = 3;
      private int optionalUint32_ ;
      /**
       * <code>optional uint32 optional_uint32 = 3;</code>
       */
      public boolean hasOptionalUint32() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 optional_uint32 = 3;</code>
       */
      public int getOptionalUint32() {
        return optionalUint32_;
      }
      /**
       * <code>optional uint32 optional_uint32 = 3;</code>
       */
      public Builder setOptionalUint32(int value) {
        bitField0_ |= 0x00000004;
        optionalUint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 optional_uint32 = 3;</code>
       */
      public Builder clearOptionalUint32() {
        bitField0_ = (bitField0_ & ~0x00000004);
        optionalUint32_ = 0;
        onChanged();
        return this;
      }

      // optional uint64 optional_uint64 = 4;
      private long optionalUint64_ ;
      /**
       * <code>optional uint64 optional_uint64 = 4;</code>
       */
      public boolean hasOptionalUint64() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 optional_uint64 = 4;</code>
       */
      public long getOptionalUint64() {
        return optionalUint64_;
      }
      /**
       * <code>optional uint64 optional_uint64 = 4;</code>
       */
      public Builder setOptionalUint64(long value) {
        bitField0_ |= 0x00000008;
        optionalUint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 optional_uint64 = 4;</code>
       */
      public Builder clearOptionalUint64() {
        bitField0_ = (bitField0_ & ~0x00000008);
        optionalUint64_ = 0L;
        onChanged();
        return this;
      }

      // optional bool optional_bool = 5;
      private boolean optionalBool_ ;
      /**
       * <code>optional bool optional_bool = 5;</code>
       */
      public boolean hasOptionalBool() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool optional_bool = 5;</code>
       */
      public boolean getOptionalBool() {
        return optionalBool_;
      }
      /**
       * <code>optional bool optional_bool = 5;</code>
       */
      public Builder setOptionalBool(boolean value) {
        bitField0_ |= 0x00000010;
        optionalBool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool optional_bool = 5;</code>
       */
      public Builder clearOptionalBool() {
        bitField0_ = (bitField0_ & ~0x00000010);
        optionalBool_ = false;
        onChanged();
        return this;
      }

      // optional float optional_float = 6;
      private float optionalFloat_ ;
      /**
       * <code>optional float optional_float = 6;</code>
       */
      public boolean hasOptionalFloat() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional float optional_float = 6;</code>
       */
      public float getOptionalFloat() {
        return optionalFloat_;
      }
      /**
       * <code>optional float optional_float = 6;</code>
       */
      public Builder setOptionalFloat(float value) {
        bitField0_ |= 0x00000020;
        optionalFloat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float optional_float = 6;</code>
       */
      public Builder clearOptionalFloat() {
        bitField0_ = (bitField0_ & ~0x00000020);
        optionalFloat_ = 0F;
        onChanged();
        return this;
      }

      // optional double optional_double = 7;
      private double optionalDouble_ ;
      /**
       * <code>optional double optional_double = 7;</code>
       */
      public boolean hasOptionalDouble() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double optional_double = 7;</code>
       */
      public double getOptionalDouble() {
        return optionalDouble_;
      }
      /**
       * <code>optional double optional_double = 7;</code>
       */
      public Builder setOptionalDouble(double value) {
        bitField0_ |= 0x00000040;
        optionalDouble_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double optional_double = 7;</code>
       */
      public Builder clearOptionalDouble() {
        bitField0_ = (bitField0_ & ~0x00000040);
        optionalDouble_ = 0D;
        onChanged();
        return this;
      }

      // optional string optional_string = 8;
      private java.lang.Object optionalString_ = "";
      /**
       * <code>optional string optional_string = 8;</code>
       */
      public boolean hasOptionalString() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string optional_string = 8;</code>
       */
      public java.lang.String getOptionalString() {
        java.lang.Object ref = optionalString_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          optionalString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string optional_string = 8;</code>
       */
      public com.google.protobuf.ByteString
          getOptionalStringBytes() {
        java.lang.Object ref = optionalString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          optionalString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string optional_string = 8;</code>
       */
      public Builder setOptionalString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        optionalString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string optional_string = 8;</code>
       */
      public Builder clearOptionalString() {
        bitField0_ = (bitField0_ & ~0x00000080);
        optionalString_ = getDefaultInstance().getOptionalString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string optional_string = 8;</code>
       */
      public Builder setOptionalStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        optionalString_ = value;
        onChanged();
        return this;
      }

      // optional bytes optional_bytes = 9;
      private com.google.protobuf.ByteString optionalBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes optional_bytes = 9;</code>
       */
      public boolean hasOptionalBytes() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bytes optional_bytes = 9;</code>
       */
      public com.google.protobuf.ByteString getOptionalBytes() {
        return optionalBytes_;
      }
      /**
       * <code>optional bytes optional_bytes = 9;</code>
       */
      public Builder setOptionalBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        optionalBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes optional_bytes = 9;</code>
       */
      public Builder clearOptionalBytes() {
        bitField0_ = (bitField0_ & ~0x00000100);
        optionalBytes_ = getDefaultInstance().getOptionalBytes();
        onChanged();
        return this;
      }

      // optional .basic.TestMessage2 optional_msg = 10;
      private basic.Basic.TestMessage2 optionalMsg_ = basic.Basic.TestMessage2.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          basic.Basic.TestMessage2, basic.Basic.TestMessage2.Builder, basic.Basic.TestMessage2OrBuilder> optionalMsgBuilder_;
      /**
       * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
       */
      public boolean hasOptionalMsg() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
       */
      public basic.Basic.TestMessage2 getOptionalMsg() {
        if (optionalMsgBuilder_ == null) {
          return optionalMsg_;
        } else {
          return optionalMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
       */
      public Builder setOptionalMsg(basic.Basic.TestMessage2 value) {
        if (optionalMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          optionalMsg_ = value;
          onChanged();
        } else {
          optionalMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
       */
      public Builder setOptionalMsg(
          basic.Basic.TestMessage2.Builder builderForValue) {
        if (optionalMsgBuilder_ == null) {
          optionalMsg_ = builderForValue.build();
          onChanged();
        } else {
          optionalMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
       */
      public Builder mergeOptionalMsg(basic.Basic.TestMessage2 value) {
        if (optionalMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              optionalMsg_ != basic.Basic.TestMessage2.getDefaultInstance()) {
            optionalMsg_ =
              basic.Basic.TestMessage2.newBuilder(optionalMsg_).mergeFrom(value).buildPartial();
          } else {
            optionalMsg_ = value;
          }
          onChanged();
        } else {
          optionalMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
       */
      public Builder clearOptionalMsg() {
        if (optionalMsgBuilder_ == null) {
          optionalMsg_ = basic.Basic.TestMessage2.getDefaultInstance();
          onChanged();
        } else {
          optionalMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      /**
       * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
       */
      public basic.Basic.TestMessage2.Builder getOptionalMsgBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getOptionalMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
       */
      public basic.Basic.TestMessage2OrBuilder getOptionalMsgOrBuilder() {
        if (optionalMsgBuilder_ != null) {
          return optionalMsgBuilder_.getMessageOrBuilder();
        } else {
          return optionalMsg_;
        }
      }
      /**
       * <code>optional .basic.TestMessage2 optional_msg = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          basic.Basic.TestMessage2, basic.Basic.TestMessage2.Builder, basic.Basic.TestMessage2OrBuilder> 
          getOptionalMsgFieldBuilder() {
        if (optionalMsgBuilder_ == null) {
          optionalMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              basic.Basic.TestMessage2, basic.Basic.TestMessage2.Builder, basic.Basic.TestMessage2OrBuilder>(
                  optionalMsg_,
                  getParentForChildren(),
                  isClean());
          optionalMsg_ = null;
        }
        return optionalMsgBuilder_;
      }

      // optional .basic.TestEnum optional_enum = 11;
      private basic.Basic.TestEnum optionalEnum_ = basic.Basic.TestEnum.Default;
      /**
       * <code>optional .basic.TestEnum optional_enum = 11;</code>
       *
       * <pre>
       *
       *
       *repeated :repeated_int32,  :int32,        12
       *repeated :repeated_int64,  :int64,        13
       *repeated :repeated_uint32, :uint32,       14
       *repeated :repeated_uint64, :uint64,       15
       *repeated :repeated_bool,   :bool,         16
       *repeated :repeated_float,  :float,        17
       *repeated :repeated_double, :double,       18
       *repeated :repeated_string, :string,       19
       *repeated :repeated_bytes,  :bytes,        20
       *repeated :repeated_msg,    :message,      21, "TestMessage2"
       *repeated :repeated_enum,   :enum,         22, "TestEnum"
       * </pre>
       */
      public boolean hasOptionalEnum() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional .basic.TestEnum optional_enum = 11;</code>
       *
       * <pre>
       *
       *
       *repeated :repeated_int32,  :int32,        12
       *repeated :repeated_int64,  :int64,        13
       *repeated :repeated_uint32, :uint32,       14
       *repeated :repeated_uint64, :uint64,       15
       *repeated :repeated_bool,   :bool,         16
       *repeated :repeated_float,  :float,        17
       *repeated :repeated_double, :double,       18
       *repeated :repeated_string, :string,       19
       *repeated :repeated_bytes,  :bytes,        20
       *repeated :repeated_msg,    :message,      21, "TestMessage2"
       *repeated :repeated_enum,   :enum,         22, "TestEnum"
       * </pre>
       */
      public basic.Basic.TestEnum getOptionalEnum() {
        return optionalEnum_;
      }
      /**
       * <code>optional .basic.TestEnum optional_enum = 11;</code>
       *
       * <pre>
       *
       *
       *repeated :repeated_int32,  :int32,        12
       *repeated :repeated_int64,  :int64,        13
       *repeated :repeated_uint32, :uint32,       14
       *repeated :repeated_uint64, :uint64,       15
       *repeated :repeated_bool,   :bool,         16
       *repeated :repeated_float,  :float,        17
       *repeated :repeated_double, :double,       18
       *repeated :repeated_string, :string,       19
       *repeated :repeated_bytes,  :bytes,        20
       *repeated :repeated_msg,    :message,      21, "TestMessage2"
       *repeated :repeated_enum,   :enum,         22, "TestEnum"
       * </pre>
       */
      public Builder setOptionalEnum(basic.Basic.TestEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000400;
        optionalEnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .basic.TestEnum optional_enum = 11;</code>
       *
       * <pre>
       *
       *
       *repeated :repeated_int32,  :int32,        12
       *repeated :repeated_int64,  :int64,        13
       *repeated :repeated_uint32, :uint32,       14
       *repeated :repeated_uint64, :uint64,       15
       *repeated :repeated_bool,   :bool,         16
       *repeated :repeated_float,  :float,        17
       *repeated :repeated_double, :double,       18
       *repeated :repeated_string, :string,       19
       *repeated :repeated_bytes,  :bytes,        20
       *repeated :repeated_msg,    :message,      21, "TestMessage2"
       *repeated :repeated_enum,   :enum,         22, "TestEnum"
       * </pre>
       */
      public Builder clearOptionalEnum() {
        bitField0_ = (bitField0_ & ~0x00000400);
        optionalEnum_ = basic.Basic.TestEnum.Default;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:basic.TestMessage)
    }

    static {
      defaultInstance = new TestMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:basic.TestMessage)
  }

  public interface TestMessage2OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 foo = 1;
    /**
     * <code>optional int32 foo = 1;</code>
     */
    boolean hasFoo();
    /**
     * <code>optional int32 foo = 1;</code>
     */
    int getFoo();
  }
  /**
   * Protobuf type {@code basic.TestMessage2}
   */
  public static final class TestMessage2 extends
      com.google.protobuf.GeneratedMessage
      implements TestMessage2OrBuilder {
    // Use TestMessage2.newBuilder() to construct.
    private TestMessage2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestMessage2(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestMessage2 defaultInstance;
    public static TestMessage2 getDefaultInstance() {
      return defaultInstance;
    }

    public TestMessage2 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestMessage2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              foo_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return basic.Basic.internal_static_basic_TestMessage2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return basic.Basic.internal_static_basic_TestMessage2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              basic.Basic.TestMessage2.class, basic.Basic.TestMessage2.Builder.class);
    }

    public static com.google.protobuf.Parser<TestMessage2> PARSER =
        new com.google.protobuf.AbstractParser<TestMessage2>() {
      public TestMessage2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestMessage2(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestMessage2> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 foo = 1;
    public static final int FOO_FIELD_NUMBER = 1;
    private int foo_;
    /**
     * <code>optional int32 foo = 1;</code>
     */
    public boolean hasFoo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 foo = 1;</code>
     */
    public int getFoo() {
      return foo_;
    }

    private void initFields() {
      foo_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, foo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, foo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static basic.Basic.TestMessage2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static basic.Basic.TestMessage2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static basic.Basic.TestMessage2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static basic.Basic.TestMessage2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static basic.Basic.TestMessage2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static basic.Basic.TestMessage2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static basic.Basic.TestMessage2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static basic.Basic.TestMessage2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static basic.Basic.TestMessage2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static basic.Basic.TestMessage2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(basic.Basic.TestMessage2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code basic.TestMessage2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements basic.Basic.TestMessage2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return basic.Basic.internal_static_basic_TestMessage2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return basic.Basic.internal_static_basic_TestMessage2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                basic.Basic.TestMessage2.class, basic.Basic.TestMessage2.Builder.class);
      }

      // Construct using basic.Basic.TestMessage2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        foo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return basic.Basic.internal_static_basic_TestMessage2_descriptor;
      }

      public basic.Basic.TestMessage2 getDefaultInstanceForType() {
        return basic.Basic.TestMessage2.getDefaultInstance();
      }

      public basic.Basic.TestMessage2 build() {
        basic.Basic.TestMessage2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public basic.Basic.TestMessage2 buildPartial() {
        basic.Basic.TestMessage2 result = new basic.Basic.TestMessage2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.foo_ = foo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof basic.Basic.TestMessage2) {
          return mergeFrom((basic.Basic.TestMessage2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(basic.Basic.TestMessage2 other) {
        if (other == basic.Basic.TestMessage2.getDefaultInstance()) return this;
        if (other.hasFoo()) {
          setFoo(other.getFoo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        basic.Basic.TestMessage2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (basic.Basic.TestMessage2) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 foo = 1;
      private int foo_ ;
      /**
       * <code>optional int32 foo = 1;</code>
       */
      public boolean hasFoo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 foo = 1;</code>
       */
      public int getFoo() {
        return foo_;
      }
      /**
       * <code>optional int32 foo = 1;</code>
       */
      public Builder setFoo(int value) {
        bitField0_ |= 0x00000001;
        foo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 foo = 1;</code>
       */
      public Builder clearFoo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        foo_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:basic.TestMessage2)
    }

    static {
      defaultInstance = new TestMessage2(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:basic.TestMessage2)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_basic_TestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_basic_TestMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_basic_TestMessage2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_basic_TestMessage2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021tests/basic.proto\022\005basic\"\273\002\n\013TestMessa" +
      "ge\022\026\n\016optional_int32\030\001 \001(\005\022\026\n\016optional_i" +
      "nt64\030\002 \001(\003\022\027\n\017optional_uint32\030\003 \001(\r\022\027\n\017o" +
      "ptional_uint64\030\004 \001(\004\022\025\n\roptional_bool\030\005 " +
      "\001(\010\022\026\n\016optional_float\030\006 \001(\002\022\027\n\017optional_" +
      "double\030\007 \001(\001\022\027\n\017optional_string\030\010 \001(\t\022\026\n" +
      "\016optional_bytes\030\t \001(\014\022)\n\014optional_msg\030\n " +
      "\001(\0132\023.basic.TestMessage2\022&\n\roptional_enu" +
      "m\030\013 \001(\0162\017.basic.TestEnum\"\033\n\014TestMessage2" +
      "\022\013\n\003foo\030\001 \001(\005*,\n\010TestEnum\022\013\n\007Default\020\000\022\005",
      "\n\001A\020\001\022\005\n\001B\020\002\022\005\n\001C\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_basic_TestMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_basic_TestMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_basic_TestMessage_descriptor,
              new java.lang.String[] { "OptionalInt32", "OptionalInt64", "OptionalUint32", "OptionalUint64", "OptionalBool", "OptionalFloat", "OptionalDouble", "OptionalString", "OptionalBytes", "OptionalMsg", "OptionalEnum", });
          internal_static_basic_TestMessage2_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_basic_TestMessage2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_basic_TestMessage2_descriptor,
              new java.lang.String[] { "Foo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
